### ISSUE TITLE
No pinctrl driver.

### ISSUE THREAD

**Issue by esmil** [revyos/th1520-linux-kernel#5]
Hi Revy.

I noticed there is no pinctrl driver available in your recent trees and none have been posted on the mailing list, so I wrote one:https://github.com/esmil/linux/commits/th1520

Can I maybe convince you to give it a test?

**Comment by RevySR** [comment]
@yuzibo Please help with testing it.

**Comment by RevySR** [comment]
It seems not work.

**Comment by esmil** [comment]
I will need a bit more information than that. I've pushed a few versions since creating this issue. The latest version changed the `function = "<number>";` to `function = "<gpio,uart, etc.>";`, so if you didn't update the device trees to do that it will fail.

**Comment by RevySR** [comment]
https://github.com/revyos/th1520-linux-kernel/tree/th1520-lts-wip

6d056139af90bf5ed0f63a5d9a204cb578c6ecef..f7792a3b375db005b772e2d5b7fa1b1789b249c3

Use this branch, init start failed.

**Comment by esmil** [comment]
Yeah, that's an older version of the driver. Try setting `CONFIG_PINCTRL_TH1520=y` so the uart driver for the boot console can get its pins.

**Comment by RevySR** [comment]
https://github.com/revyos/th1520-linux-kernel/commits/th1520-lts-wip/

Using the latest version of the patch, but the second ethernet port still doesn't work.

**Comment by esmil** [comment]
I don't immediately see what the problem is. It works on my [th1520](https://github.com/esmil/linux/commits/th1520) branch. Maybe you could try that branch to see if it's a device tree problem or a config problem.

**Comment by RevySR** [comment]
https://github.com/revyos/th1520-linux-kernel/tree/th1520-master

it works for dual ethernet.

**Comment by RevySR** [comment]
https://github.com/revyos/th1520-linux-kernel/tree/th1520-lts-wip-new

backport from th1520 branch, it doesn't work.

**Comment by RevySR** [comment]
https://github.com/revyos/th1520-linux-kernel/tree/th1520-lts

Now, it works
